---
# TODO: Consider adding "upgrade=full" to also update everything.
- name: Ensure apt cache is updated.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure correct kernel headers are installed.
  shell: "apt-get -y install linux-headers-$(uname -r)"

- name: Add configuration to update apt cache on boot.
  copy:
    src: refresh-apt.conf
    dest: /etc/init/refresh-apt.conf
    owner: root
    group: root
    mode: 0644

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^UseDNS', line: 'UseDNS no' }
    - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

# Vagrant SSH configuration.
- name: Configure Vagrant .ssh directory.
  file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

- name: Get Vagrant's public key.
  get_url:
    url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600

# VirtualBox tools installation.
- name: Check if VirtualBox is running the guest VM.
  stat: path=/home/vagrant/.vbox_version
  register: virtualbox_check

- include: virtualbox.yml
  when: virtualbox_check.stat.exists

# VMware tools installation.
- name: Check if VMWare is running the guest VM.
  shell: "cat /proc/scsi/scsi | grep VMware"
  changed_when: false
  failed_when: false
  register: vmware_check

- include: vmware.yml
  when: vmware_check.rc == 0

# Cleanup tasks.
- name: Remove unneeded packages.
  apt: "pkg={{ item }} state=absent"
  with_items:
    - ppp
    - pppconfig
    - pppoeconf
    - cpp
    - gcc
    - g++
    - libx11-data
    - xauth
    - libxmuu1
    - libxcb1
    - libx11-6
    - libxext6
    - linux-source

- name: Remove uneeded packages (by regex).
  shell: "apt-get -y remove '.*-dev$'"

- name: Clean up apt.
  command: "{{ item }}"
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean
